spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: HOODFILLER-SERVICE
          uri: lb://HOODFILLER-SERVICE
          predicates:
            - Path=/hoodfiller/**


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 9191